// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

//import (
//	"time"
//)
//
//type Follow struct {
//	Follower  *User      `json:"follower"`
//	Following *User      `json:"following"`
//	CreatedAt *time.Time `json:"createdAt,omitempty"`
//}
//
//type LoginUser struct {
//	Email    string `json:"email"`
//	Password string `json:"password"`
//}
//
//type NewFollow struct {
//	Follower  string `json:"follower"`
//	Following string `json:"following"`
//}
//
//type NewUser struct {
//	Name      string     `json:"name"`
//	Email     string     `json:"email"`
//	Username  string     `json:"username"`
//	Password  *string    `json:"password,omitempty"`
//	Biography *string    `json:"biography,omitempty"`
//	Location  *string    `json:"location,omitempty"`
//	Website   *string    `json:"website,omitempty"`
//	Dob       *time.Time `json:"dob,omitempty"`
//}
//
//type Tweet struct {
//	ID        string    `json:"ID"`
//	User      *User     `json:"user"`
//	Content   string    `json:"content"`
//	CreatedAt time.Time `json:"createdAt"`
//}
//
//type User struct {
//	ID         string     `json:"id"`
//	Name       string     `json:"name"`
//	Username   string     `json:"username"`
//	Email      string     `json:"email"`
//	CreatedAt  time.Time  `json:"createdAt"`
//	Profile    *string    `json:"profile,omitempty"`
//	Background *string    `json:"background,omitempty"`
//	Biography  *string    `json:"biography,omitempty"`
//	Location   *string    `json:"location,omitempty"`
//	Website    *string    `json:"website,omitempty"`
//	Dob        *time.Time `json:"dob,omitempty"`
//	Followers  *int       `json:"followers,omitempty"`
//	Following  *int       `json:"following,omitempty"`
//}
//
//type UserAuth struct {
//	User  *User  `json:"user"`
//	Token string `json:"token"`
//}
//
//type NewTweet struct {
//	Content string `json:"content"`
//}
