// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

//import (
//	"time"
//
//	"github.com/99designs/gqlgen/graphql"
//)

//type Follow struct {
//	Follower  *User      `json:"follower"`
//	Following *User      `json:"following"`
//	CreatedAt *time.Time `json:"createdAt,omitempty"`
//}
//
//type LoginUser struct {
//	Email    string `json:"email"`
//	Password string `json:"password"`
//}
//
//type NewFollow struct {
//	Follower  string `json:"follower"`
//	Following string `json:"following"`
//}
//
//type NewUser struct {
//	Name     string `json:"name"`
//	Email    string `json:"email"`
//	Username string `json:"username"`
//	Password string `json:"password"`
//}
//
//type Tweet struct {
//	ID      string `json:"ID"`
//	User    *User  `json:"user"`
//	Title   string `json:"title"`
//	Content string `json:"content"`
//}
//
//type User struct {
//	ID        string          `json:"id"`
//	Name      string          `json:"name"`
//	Username  string          `json:"username"`
//	Email     string          `json:"email"`
//	Dob       *time.Time      `json:"dob,omitempty"`
//	Content   *string         `json:"content,omitempty"`
//	Profile   *graphql.Upload `json:"profile,omitempty"`
//	CreatedAt *time.Time      `json:"createdAt,omitempty"`
//	Followers []*Follow       `json:"followers,omitempty"`
//	Following []*Follow       `json:"following,omitempty"`
//}
//
//type NewTweet struct {
//	UserID  string `json:"userID"`
//	Title   string `json:"title"`
//	Content string `json:"content"`
//}
