// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewUser struct {
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Username  string     `json:"username"`
	Password  *string    `json:"password,omitempty"`
	Biography *string    `json:"biography,omitempty"`
	Location  *string    `json:"location,omitempty"`
	Website   *string    `json:"website,omitempty"`
	Dob       *time.Time `json:"dob,omitempty"`
}

type Follow struct {
	FollowerID  string     `json:"followerID" gorm:"primaryKey"`
	FollowingID string     `json:"followingID" gorm:"primaryKey"`
	Follower    *User      `json:"follower" gorm:"foreignKey:FollowerID;references:ID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
	Following   *User      `json:"following" gorm:"foreignKey:FollowingID;references:ID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
}

type NewFollow struct {
	Follower  string `json:"follower"`
	Following string `json:"following"`
}

type User struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Username  string     `json:"username"`
	Password  string     `json:"password"`
	CreatedAt time.Time  `json:"createdAt"`
	Biography *string    `json:"biography,omitempty"`
	Location  *string    `json:"location,omitempty"`
	Website   *string    `json:"website,omitempty"`
	Dob       *time.Time `json:"dob,omitempty"`
	Followers *int       `json:"followers,omitempty"`
	Following *int       `json:"following,omitempty"`
}
