// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
	"time"
)

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewUser struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Follow struct {
	FollowerID  string     `json:"followerID" gorm:"primaryKey"`
	Follower    *User      `json:"follower" gorm:"foreignKey:FollowerID;references:ID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
	FollowingID string     `json:"followingID" gorm:"primaryKey"`
	Following   *User      `json:"following" gorm:"foreignKey:FollowingID;references:ID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
}

type NewFollow struct {
	Follower  string `json:"follower"`
	Following string `json:"following"`
}

type User struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Email     string          `json:"email"`
	Username  string          `json:"username"`
	Password  string          `json:"password"`
	Dob       *time.Time      `json:"dob,omitempty"`
	Content   *string         `json:"content,omitempty"`
	Profile   *graphql.Upload `json:"profile,omitempty"`
	CreatedAt *time.Time      `json:"createdAt,omitempty"`
	Followers []*Follow       `json:"followers,omitempty"`
	Following []*Follow       `json:"following,omitempty"`
}
